services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: somepassword
    networks:
      - my-network
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:1.0
    env_file:
    - .env
    restart: on-failure
    container_name: myapp-container
    ports:
      - "80:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - my-network
    cpus: 0.5  # CPU 제한 (0.5 vCPU)
    mem_limit: "1g"  # 메모리 제한 (1GB)
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network:
