services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: somepassword
    networks:
      - my-network
  myapp:
    build:
      context: .
      dockerfile: deploy-Dockerfile
    image: myapp:1.0
    restart: on-failure
    container_name: myapp-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network
networks:
  my-network:
