spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/testdb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: false
          show_sql: false