### performance 받기
GET http://localhost/api/v1/performance/search
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=NzBkOTlhYTktNGI3My00YWMzLTg2NDQtMzE0ZjM3M2EwZThlLDcwZDk5YWE5LTRiNzMtNGFjMy04NjQ0LTMxNGYzNzNhMGU4ZQ==
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=MGY5NGY1MTAtZDMxYS00MjdmLTg4M2YtM2UyMGRmMWIyNDkyLDBmOTRmNTEwLWQzMWEtNDI3Zi04ODNmLTNlMjBkZjFiMjQ5Mg==
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=MDkxZTY3YWItNDRiOS00NjlmLTk1NGYtMWFmZjhmNjcwYjI2LDA5MWU2N2FiLTQ0YjktNDY5Zi05NTRmLTFhZmY4ZjY3MGIyNg==
Accept: application/json

### 회원가입(USER)
POST http://localhost:80/api/v1/local/signup
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678",
  "nickname": "examplename",
  "phoneNumber": "010-0000-0000",
  "email": "test@example.com"
}

### 로그인
POST http://localhost:80/api/v1/local/signin
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678"
}

### 댓글 쓰기
POST http://localhost/api/v1/performance/f1c7da85-c5a3-4c38-b3d6-993ef245ab84/review
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTRlYTU0OS1hMTQxLTRmMTktYWE0NC05MGIyODI3Nzg0YTYiLCJpYXQiOjE3MzgyMTY3NTQsImV4cCI6MTczODIxNzY1NH0.931yggANm302o8VZbENqFNQDbJ-k1FlbMzeFoFS2HQo
Content-Type: application/json

{
  "rating": 5,
  "title": "Good",
  "content": "very good"
}

### 댓글 조회
GET http://localhost/api/v2/performance/f1c7da85-c5a3-4c38-b3d6-993ef245ab84/review
Content-Type: application/json
