### performance 받기
GET http://localhost/api/v1/performance/search
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=NzBkOTlhYTktNGI3My00YWMzLTg2NDQtMzE0ZjM3M2EwZThlLDcwZDk5YWE5LTRiNzMtNGFjMy04NjQ0LTMxNGYzNzNhMGU4ZQ==
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=MGY5NGY1MTAtZDMxYS00MjdmLTg4M2YtM2UyMGRmMWIyNDkyLDBmOTRmNTEwLWQzMWEtNDI3Zi04ODNmLTNlMjBkZjFiMjQ5Mg==
Accept: application/json

### 다음 cursor로 요청
GET http://localhost/api/v1/performance/search?cursor=MDkxZTY3YWItNDRiOS00NjlmLTk1NGYtMWFmZjhmNjcwYjI2LDA5MWU2N2FiLTQ0YjktNDY5Zi05NTRmLTFhZmY4ZjY3MGIyNg==
Accept: application/json

### 회원가입(USER)
POST http://localhost:80/api/v1/local/signup
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678",
  "nickname": "examplename",
  "phoneNumber": "010-0000-0000",
  "email": "test@example.com"
}

### 로그인
POST http://localhost:80/api/v1/local/signin
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678"
}

### 댓글 쓰기
POST http://localhost/api/v1/performance/f8d31155-8243-48a8-a060-3306b52fa227/review
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0ZjhmZWQ0OC1mMzUyLTRlNzItOWFjYi05ZTUzZDc2YWNlMzYiLCJpYXQiOjE3MzgyMTk4MDMsImV4cCI6MTczODIyMDcwM30.lX6Ory8LVzsc494R1_q_OtMJSRWpsVvWV-Jo8DysR7M
Content-Type: application/json

{
  "rating": 5,
  "title": "3rd Good",
  "content": "very good"
}

### 댓글 조회
GET http://localhost/api/v2/performance/f8d31155-8243-48a8-a060-3306b52fa227/review
Content-Type: application/json

### 커서와 함께 댓글 조회
GET http://localhost/api/v2/performance/f8d31155-8243-48a8-a060-3306b52fa227/review?cursor=MjAyNS0wMS0zMFQwNjo1MDo0MC45MzU1OTBaLGE1NzgxMTU4LWE3ODEtNGE5Ni1hNDM2LTA1MjY3MzQ5OWE4NQ==
Content-Type: application/json

### 커서와 함께 한번더 댓글 조회
GET http://localhost/api/v2/performance/f8d31155-8243-48a8-a060-3306b52fa227/review?cursor=MjAyNS0wMS0zMFQwNjo1MDozMy4wMDY4NjdaLDIwZGU2NWE2LThkNWYtNDE2My1iOTkzLWExMjIyYjFjNGMzZQ==
Content-Type: application/json
