### 회원가입
POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678",
  "nickname": "examplename",
  "phoneNumber": "010-0000-0000",
  "email": "test@example.com"
}

### 로그인
POST http://localhost:8080/api/v1/signin
Content-Type: application/json

{
  "username": "correct",
  "password": "12345678"
}

### pingpong
GET http://localhost:8080/api/v1/ping
Accept: application/json

### 인증 토큰으로 유저 프로필 조회
GET http://localhost:8080/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiY2JlMjI5Yi0zYjgyLTRkM2MtOWFjNS03ZWYzZTUyMjViNWYiLCJpYXQiOjE3MzYzMjA2MDksImV4cCI6MTczNjMyMTUwOX0.RJHC9qQvBnt_q4aS81qdpTrTnXfS-qQ-wMygRFXXg8E